30, 30, 92
....W.MW.F...W.W..F..F.F.F...
F.MMMF.W.FW.WFWWWMWWFWW.WM.WM
W.WM..WMM.FM.F......MMFWFW.F.
.FFM.MF..WM.M.WW...WWW.W.W.F.
..WM.WF...FW.F.W..W.WF....WW.
.F..M.MF...F..MFMF...W.WWW.FM
W..W.FMFMMF.....W.F.F.F...WMW
F.WWW..W..F..W.MMM...M..MWW.M
WW.WF...FFMWM.F.F....WW..W.FM
MWWW.MMMF.M..FM.W.MW.WMWM...F
....W.WMF.WFW.F.W.F....M.F...
W..W.W.FWF.WWMFMMF..M..MM.WMM
FF....M..M....F..WF.....FF...
M.....W.W.M..W.FF..FM..MFM.MM
M.FMM.M...W.MFWMFFW.F.W.M.FFF
WWWF.MWMWF....W.......W..FFMM
W..M...F.FW.WWWF..MM.WF.W..FF
M.MFMW....FWF..MW..MM.F..M...
..F.MF...F..MW.WF....MWM..FFF
.W............M..FFMMM.F.W.W.
.MM.W..MW...MMFM.W..M..M..W..
.F......MW...FFWF.M..WMFM.MF.
.MWFM.M.WW.W...WM.MMFWF.F.F..
FWF..F...WFFFM.F...W.........
..W.M..FF.M...M.F...FF.M..FW.
..WMF..WWWWFF...M.WM..W.....F
.FFM...MFM...MM......W.M..W.F
.FWMFF.WMFFFMFW.......F.MW.FM
FF..M...F.W.W.WMWMFF.M.MFM.M.

